apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACC_ID>:role/AmazonEKSLoadBalancerControllerRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACC_ID>:role/AmazonEKSAutoScalerRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACC_ID>:role/FluentBitRole






# {
#     "Version": "2012-10-17",
#     "Id": "Policy1614277390150",
#     "Statement": [
#         {
#             "Sid": "AllowRootAccess",
#             "Effect": "Allow",
#             "Principal": {
#                 "AWS": "arn:aws:iam::339712938758:role/FluentBitRole"
#             },
#             "Action": [
#                 "elasticfilesystem:ClientMount",
#                 "elasticfilesystem:ClientWrite",
#                 "elasticfilesystem:ClientRootAccess"
#             ],
#             "Resource": "arn:aws:elasticfilesystem:us-east-1:339712938758:file-system/fs-016de2fc71efb86af",
#             "Condition": {
#                 "Bool": {
#                     "elasticfilesystem:AccessedViaMountTarget": "true"
#                 }
#             }
#         }
#     ]
# }